import BarChart from '@/components/BarChart.tsx';
import RecentOrders from '@/components/RecentOrders';
import TopCards from '@/components/TopCards';
import Head from 'next/head';
import Image from 'next/image';
import Header from '../components/Header';

export default function Home() {
  const headerTitle = 'Dashboard';
  return (
    <>
      <Head>
        <title>Dashboard using NextJS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gray-200 min-h-screen">
        <Header title={headerTitle} />
        <TopCards />
        <div className="p-4 grid md:grid-cols-3 grid-cols-1 gap-4">
          <BarChart />
          <RecentOrders />
        </div>
      </main>
    </>
  );
}
